In [1]:
import numpy as np

# Matrices simples

In [ ]:
# Déclaration d'une matrice
A = np.array([[1, 2], [3, 4], [5, 6]], dtype=np.int16)
# Le paramètre dtype est facultatif. Il permet de préciser le type de donnée.
# Ce paramètre est valable pour tous les constructeurs
# Le type peut être int8, int16, int32, int64, uint8, ..., float8, float64, etc. (cf. documentation)
A

In [ ]:
# Taille de la matrice
A.shape

In [ ]:
# Transposée d'une matrice
A.T

In [ ]:
# Matrice remplie de 1 ou de 0
B = np.ones((2, 3))
B = np.zeros((2, 3))
B

In [ ]:
# Valeurs aléatoires
np.random.seed(5543)    # Si cette ligne est précisée, les valeurs aléatoires sont tjs les mêmes
B = np.random.randn(2,3)   # Génération aléatoire selon une loi normal. Il existe d'autres générateurs
B


In [ ]:
# Valeurs réparties
B = np.linspace(0, 10, 20)   # Génère 20 valeurs de 0 à 10 uniformément réparties
print(B)
B = np.arange(0, 10, 2)   # Génère des valeurs de 0 à 10 avec un pas de 2
print(B)

In [51]:
# Broadcasting
A = np.random.randn(5,4)
B = np.random.randn(5,4)
C = np.random.randn(5,1)
A + B    # Ajoute les tableaux A & B
A + 3    # Ajoute 3 à toutes les valeurs de A
A + C    # Ajoute le vecteur C à toutes les colonnes de A
         # C'est ça le broadcasting
         # Le vecteur C est étendu pour correspondre aux dim de A
         # Cela fonctionne uniquement car une des 2 dim correspond & l'autre vaut 1


array([[ 0.35979228,  0.06178958,  1.27200651, -0.02664759],
       [ 1.02949056,  0.99887415, -0.02459463, -2.83833197],
       [-2.21973886,  0.38906052, -1.19012987,  0.73592745],
       [ 0.2120802 ,  0.70635418, -1.06921109,  0.56394508],
       [ 1.08135278,  1.86749699, -0.8421386 , -0.70782023]])

# Manipulation sur les tableaux

In [3]:
A = np.ones((2,2))
B = np.zeros((2,2))

In [ ]:
# Concatenation de tableaux
#============================
# Concaténation horizontale
C = np.hstack((A, B))
print(C)
# Concaténation verticale
C = np.vstack((A, B))
print(C)
# Concaténation générique selon un axe donné. Utile pour des dimensions >2
C = np.concatenate((A, B), axis=1)
print(C)

In [ ]:
# Re formate un tableau
D = C.reshape((4,2))    # Le nombre d'éléments avant et après formattage doit être identique
print(D)
# Squeeze = Supprimes les dimensions = 1
A = np.ones((5,1))
print(np.squeeze(A).shape)
# Ravel:Applati un tableau
print(D.ravel())

In [ ]:
# Produit matriciel
C = B.dot(A)
C

In [26]:
# Slicing
#========
A = np.ones((6,10))
A = np.array([i for i in range(60)]).reshape((6, 10))

print(A)
A[:,0]    # Tous les éléments de la première colonne
A[2:4,5]  # Les lignes 2 à 4 (4 exclue) de la 6è colonne (index 5)
A[:3,5]   # Les premières lignes de la colonne 5
A[3:,5]   # De la 3e ligne à la dernière de la 5è colonne
A[3:,5:7] # De la 3e ligne à la dernière des colonnes 5 à 7 (7e exclue)
A[1:-1,:] # De la colonne 1 à la dernière exclue
A[1:-2:2,:]  # De la colonne 1 à l'avant-avant-dernière colonne (exclue), 1 valeur sur 2

# Note: on peut modifier certaines valeurs précises avec ces notations
A[0,:] = 99   # La première colonne est entièrement mise à 99
B = np.zeros((5, 5))
B[::2,::2] = 1
print(B)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]]
[[ 1.  0.  1.  0.  1.]
 [ 0.  0.  0.  0.  0.]
 [ 1.  0.  1.  0.  1.]
 [ 0.  0.  0.  0.  0.]
 [ 1.  0.  1.  0.  1.]]


In [30]:
# Boolean indexing
A = np.random.randint(0, 10, [5, 5])
# Faire une opération de comparaison sur cette matrice donne une matrice de dim équivalente mais 
# contenant des boolééens selon le résultat de la comparaison
print(A < 5)

# On peut ensuite réinjecter ce résultat pour accéder seulement certaines valeurs de la matrice
A[A<5] = 0    # Force à 0 toutes les valeurs de la matrice qui sont <5
print(A)

[[ True  True False False  True]
 [False False False  True False]
 [False  True  True False  True]
 [ True False False  True False]
 [False  True  True  True  True]]
[[0 0 9 8 0]
 [6 6 7 0 6]
 [8 0 0 8 0]
 [0 7 6 0 5]
 [8 0 0 0 0]]


# Fonctions mathématiques

## Méthodes de la classe NDarray

In [37]:
A = np.random.randint(0, 10, [5, 3])
A.sum()         # La somme de tous les éléments du tableau
A.sum(axis=0)   # La somme de tous les éléments du tableau selon l'axe 0 (la somme de toutes les colonnes)
A.cumsum()      # Somme cumulée (argument axis disponible)
A.prod()        # Le produit de tous les éléments du tableau (argument axis disponible)
A.cumprod()     # Produit cumulé
A.min()         # La valeur mini du tableau
A.max()         # La valeur max
A.mean()        # La valeur moyenne
A.std()         # Ecart type
A.var()         # Variance
A.argmin()      # Retourne la position de la valeur mini
A.argmax()      # Retourne la position de la valeur maxi
A.sort()        # Trie le tableau
A.argsort()     # Donnes les position dans l'ordre pour trier le tableau

# Lib mathématique
np.exp(A)
np.sin(A)
# Les méthodes pour réaliser des fonction mathématiques ne sont pas des méthodes membres de la classe
# NDarray. Il faut les appeler comme cela.


array([[ 0.84147098,  0.90929743,  0.98935825],
       [ 0.90929743, -0.95892427,  0.98935825],
       [ 0.14112001, -0.2794155 , -0.2794155 ],
       [-0.2794155 ,  0.98935825,  0.98935825],
       [ 0.14112001, -0.95892427, -0.95892427]])

## Routines
Beaucoup de fonctions permettant des calculs mathématiques ou statistiques ne sont pas des méthodes de la classe NDarray mais sont intégrées en tant que _routines_ dans le module NumPy.
Ces fonctions s'appellent comme suit:
```np.<fonction>(<tableau>)```
### Mathématiques
cf. doc officielle https://numpy.org/doc/stable/reference/routines.math.html

In [ ]:
np.exp(A)
np.sin(A)
# etc.

### Statistiques
cf. doc officielle https://numpy.org/doc/stable/reference/routines.statistics.html

In [43]:
A = np.random.randint(0, 10, [5, 5])
np.corrcoef(A)    # Coeff de corrélation
np.unique(A, return_counts=True)   # Liste des éléments uniques contenus dans le tableau avec leur frequence
values, counts = np.unique(A, return_counts=True)
values[counts.argsort()]   # La liste des valeurs de la matrice triée par fréquence d'apparition croissante

np.median(A)    # Valeur mediane
np.nanmean(A)   # Valeur moyenne mais en ignorant les valeur NaN
# la version NaN existe pour min, max, median, var, std, etc.
np.isnan(A)     # Renvoie un masque qui indique les valeurs NaN

# etc.

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]], dtype=bool)